version: '3.8'

services:
  app:
    image: youva1/my-ml-app
    ports:
      - "5000:5000"
    command: >
      sh -c "while [ ! -f models/RF.pkl ]; do echo 'Waiting for model...'; sleep 5; done; python3 main.py serve --load_model models/RF.pkl --port 5000"
    depends_on:
      - pipeline
    volumes:
      - ./models:/app/models  

  pipeline:
    image: youva1/my-ml-app
    command: ["python3", "run_pipeline.py"]
    volumes:
      - ./models:/app/models  # Ensure the model is saved here
