FROM python:3.11.5

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements.txt and install dependencies
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Expose the port Flask will be running on (default Flask port is 5000)
EXPOSE 5000

# Set environment variable for the port (default 5000)
ENV PORT 5000

# Run the Flask application with the 'serve' command if specified
CMD ["python3", "main.py", "serve", "--load_model", "models/RF.pkl", "--port", "5000"]
