FROM python:3.11.5
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY run_pipeline.py model_pipline.py ./
EXPOSE 5001
CMD ["bash", "-c", "python3 run_pipeline.py --train_data churn-bigml-80.csv --test_data churn-bigml-20.csv --model RF --save_model models/RF.pkl"]