pipeline {
    agent any
    environment {
        ACCURACY_THRESHOLD = '0.85'
        ROC_AUC_THRESHOLD = '0.80'
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/Youssef-Kharroubi/ML-OPS', branch: 'main'
            }
        }
        stage('Build Pipeline Image') {
            steps {
                sh 'docker build -t ml-ops-pipeline -f modelPipeline/Dockerfile.pipeline modelPipeline/'
            }
        }
        stage('Run Pipeline') {
            steps {
                sh '''
                docker run --rm \
                    -e ACCURACY_THRESHOLD=${ACCURACY_THRESHOLD} \
                    -e ROC_AUC_THRESHOLD=${ROC_AUC_THRESHOLD} \
                    -v $(pwd)/models:/app/models \
                    -v $(pwd)/modelPipeline/data:/app/data \
                    -v $(pwd)/mlruns:/app/mlruns \
                    ml-ops-pipeline
                '''
            }
        }
    }
    post {
        always {
            echo 'Pipeline completed'
        }
    }
}